### ISSUE TITLE
--net option breaks when using resolvconf (/etc/resolv.conf symlink)

### ISSUE THREAD

**Issue by jbernard** [vincentbernat/eudyptula-boot#1]
Heya, this is quite nice, thank you for putting it all together.

I noticed that the `--net` option fails when the host is using resolvconf (which uses a symlink to dynamically change /etc/resolv.conf).

```
[✔] udev started.
[…] Configure network... mount: mount point /etc/resolv.conf is a symbolic link to nowhere
[    0.573254] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00002000                                 
```

**Comment by vincentbernat** [comment]
I have pushed a commit to fix that. Tell me if it doesn't work.

Thanks!

**Comment by jbernard** [comment]
Thanks, that suceeds in bringing up the interface.  Hostname lookup works, but ping does not seem to work… I think perhaps there's something on the host configuration needed for this to work, or am I missing something?

**Comment by vincentbernat** [comment]
❦ 12 janvier 2015 11:44 -0800, Jon Bernard notifications@github.com :

> Thanks, that suceeds in bringing up the interface. Hostname lookup
> works, but ping does not seem to work… I think perhaps there's
> something on the host configuration needed for this to work, or am I
> missing something?

Don't try ping. It is using the user mode network stack and it is not
possible to use ICMP with this one. Check with `curl www.google.com`

## that everything works as expected.

Avoid temporary variables.
            - The Elements of Programming Style (Kernighan & Plauger)
