### ISSUE TITLE
[⚡] Unable to find module overlayfs!

### ISSUE THREAD

**Issue by jbernard** [vincentbernat/eudyptula-boot#2]
On a 3.19-rc4 kernel, I've compiled overlayfs as module and it's located in `./lib/modules/3.19.0-rc4/kernel/fs/overlayfs/overlay.ko`  But I see `[⚡] Unable to find module overlayfs!` during boot.  Perhaps the name `overlay` instead of `overlayfs` is causing confusion?

**Comment by vincentbernat** [comment]
I thought I already fixed that but you are right, the module name was incorrect.

**Comment by jbernard** [comment]
With that commit, I'm now seeing this:

```
[✔] Found kernel 3.19.0-rc4.
[✔] Kernel configuration checked. overlayfs present.
[✔] Modules are in /tmp/kernel-dev/lib/modules/3.19.0-rc4.
[✔] All dependencies are met.
[∗] TMP is /tmp/tmp.XmGBuCRtdt.
[…] Build initrd... mkdir: cannot create directory `/tmp/tmp.XmGBuCRtdt/initrd/tmp': File exists
```

The error goes away if I revert that commit.

**Comment by jbernard** [comment]
So, adding `-p` to mkdir on line 236 allows a successful boot, but the root overlay appears to be missing:

```
➜  mount
rootshare on / type 9p (ro,relatime,sync,dirsync,trans=virtio,version=9p2000.u)
tmpfs on /run type tmpfs (rw,nosuid,nodev,relatime)
tmpfs on /var/tmp type tmpfs (rw,nosuid,nodev,relatime)
tmpfs on /var/log type tmpfs (rw,nosuid,nodev,relatime)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,relatime)
proc on /proc type proc (rw,relatime)
sys on /sys type sysfs (rw,relatime)
homeshare on /root type 9p (rw,relatime,sync,dirsync,trans=virtio,version=9p2000.L,access=0)
moduleshare on /lib/modules type 9p (ro,relatime,sync,dirsync,trans=virtio,version=9p2000.L,access=0)
configshare on /tmp/config type 9p (rw,relatime,sync,dirsync,trans=virtio,version=9p2000.u,access=0)
devtmpfs on /dev type devtmpfs (rw,relatime,size=10240k,nr_inodes=13696,mode=755)
devpts on /dev/pts type devpts (rw,relatime,mode=600)
```

**Comment by vincentbernat** [comment]
That's odd that you already have a `tmp` there. Would you mind adding a `ls -l ${DESTDIR}` and `ls -l ${DESTDIR}/tmp` before line 236?

**Comment by vincentbernat** [comment]
The problem with the overlay is that I have very badly tested the support of overlayfs... I am fixing that now.

**Comment by vincentbernat** [comment]
OK, I have fixed the overlayfs thing. Please, try again. I have also added your fix for `${DESTDIR}/tmp`. It happened because your modules are in `/tmp`.

**Comment by jbernard** [comment]
Yep, this works great, thanks!

I did also test on Arch and it almost works there with two exceptions.  Arch differs from recent Debian in that they don't provide convenience symlinks for udev and agetty.
1. The call to `/sbin/getty` should be `/sbin/agetty`, the util-linux package ships agetty and I believe debian copies it to getty to help maintain everyone's sanity.  They don't do this in Arch, so the terminal will fail.
2. Udev was merged into systemd and while Debian maintains a symlink from `/sbin/udevd` to `/lib/systemd/systemd-udevd`, Arch does not.  A solution could be to first check for the systemd location and then fall back to the older udevd if not found.

Other than those two issue, everything works great on Debian Wheezy, Jessie, and latest Arch.  Thanks again, I'm also working on the Eudyptula Challenge and this makes my life much easier.

**Comment by jbernard** [comment]
To be more precise, this patch allows correct execution on Arch (without breaking Debian):

```
diff --git a/eudyptula-boot b/eudyptula-boot
index 78ee5fe..e07aafc 100755
--- a/eudyptula-boot
+++ b/eudyptula-boot
@@ -418,7 +418,7 @@ case $$,$STATE in
         udev_log=err
         mount -n -o size=10M,mode=0755 -t devtmpfs devtmpfs /dev
         udevadm info --cleanup-db
-        udevd --daemon
+        /lib/systemd/systemd-udevd --daemon
         udevadm trigger --action=add
         udevadm settle
         mkdir -p /dev/pts
@@ -464,7 +464,7 @@ case $$,$STATE in

         log_info_msg "Setup terminal"
         export STATE=GETTY
-        exec setsid /sbin/getty -n -L ttyS0 -a root -l /tmp/init -i 115200 $TERM
+        exec setsid /sbin/agetty -n -L ttyS0 -a root -l /tmp/init -i 115200 $TERM
         ;;

     1,GETTY)
```

**Comment by vincentbernat** [comment]
Thanks, I have pushed two commits with those modifications.
