### ISSUE TITLE
Use systemd-udevd in /usr

### ISSUE THREAD

**Issue by petergil** [vincentbernat/eudyptula-boot#3]
Please use the systemd-udevd path /usr/lib/systemd/systemd-udevd instead of  /lib/systemd/systemd-udevd, since that is where it's expected to be installed (not all distros have made /lib a symlink to /usr/lib).

**Comment by vincentbernat** [comment]
❦ 25 janvier 2015 06:50 -0800, Peter Gille notifications@github.com :

> Please use the systemd-udevd path /usr/lib/systemd/systemd-udevd
> instead of /lib/systemd/systemd-udevd, since that is where it's
> expected to be installed (not all distros have made /lib a symlink to
> /usr/lib).

It seems to be distro-dependent (even on distro not symlinking). I have

## added a commit to also look into /usr/lib/systemd.

Don't use conditional branches as a substitute for a logical expression.
            - The Elements of Programming Style (Kernighan & Plauger)
