### ISSUE TITLE
Tested with qemu 2.5?

### ISSUE THREAD

**Issue by jbernard** [vincentbernat/eudyptula-boot#6]
Do you see sigsegv with qemu 2.5?  I haven't had a chance to debug it yet, but I don't see it with 2.4.  Just curious if you've tested it as well.

Cheers

**Comment by vincentbernat** [comment]
Yes, there is a bug with 9P in 2.5. See: http://thread.gmane.org/gmane.comp.emulators.qemu/383093

**Comment by jbernard** [comment]
Thanks.  Seems to be a certain combination of options: http://lists.nongnu.org/archive/html/qemu-devel/2015-12/msg03633.html
