### ISSUE TITLE
linux-next, 9p mounts fail

### ISSUE THREAD

**Issue by jbernard** [vincentbernat/eudyptula-boot#8]
[∗] initrd started.
[…] Load configuration... mount: mounting configshare on /tmp/config failed: Invalid argument
[✘] Unable to load configuration!
Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000100

I'm not entirely sure when this started, but it appears to fail on all of the 9p config mounts.  What additional information might you need?

**Comment by vincentbernat** [comment]
It works for me with 4.18.0-1-amd64. I get some warnings since 4.17:

```
[    0.457242] FS-Cache: Duplicate cookie detected
[    0.457627] FS-Cache: O-cookie c=(____ptrval____) [p=(____ptrval____) fl=226 nc=0 na=1]
[    0.458278] FS-Cache: O-cookie d=(____ptrval____) n=(____ptrval____)
[    0.458792] FS-Cache: O-key=[8] '3601000000000000'
[    0.459189] FS-Cache: N-cookie c=(____ptrval____) [p=(____ptrval____) fl=2 nc=0 na=1]
[    0.459830] FS-Cache: N-cookie d=(____ptrval____) n=(____ptrval____)
[    0.460357] FS-Cache: N-key=[8] '3601000000000000'
```

It happens at the same time you get your error. Do you run `eudyptula-boot` without any argument?

**Comment by jbernard** [comment]
With no arguments (the system 4.18.0-1 kernel) I see:

    [∗] Setup terminal.
    […] Setup terminal size... stty: invalid integer argument: ''
    [    2.091281] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000100

With only one argument (a bzImage), I see:

    sh: 1: /tmp/config/exec: /home/jbernard/linux/arch/x86/boot/bzImage: Permission denied
    [    1.512436] sysrq: SysRq : Resetting
    [∗] VM terminated.

What have I done to my machine? ;)  The permission error is strange, the bzImage (and entire directory hierarchy) is owned by me (jbernard), so there isn't and obvious permission problem on the host.

I do also see the FS-Cache messages you pointed out before my other errors.

I'm happy to iterate and help debug, this tool is very useful to me.  Huge thanks for writing and maintaining it, I really appreciate your work.

**Comment by vincentbernat** [comment]
For the stty issue, which terminal are you using? If you use this in a shel, do you get something back?

```
printf '\0337\033[r\033[999;999H\033[6n\0338'
```

Nonetheless, I've just pushed a commit to workaround this issue.

As for the second issue, you an specify a kernel with `--kernel=...`. Otherwise, additional arguments are interpreted as commands to execute inside the VM.

**Comment by jbernard** [comment]
With your last 3 commits, the stty issue is resolved.  I forgot `-k`, sorry about that.  Now, the system kernel is successful, but my custom kernel fails with an invalid mount option.  So I suspect there is a problem with the `.config`.  I'm starting with `make tinyconfig` and then `minimal-configuration debug` to achieve a minimal configuration, followed by `make`.  Every option mentioned in README.md is present, so there must be something new that has changed or different.

Is the way I'm generating a `.config` valid?  I'm curious if these steps yield a bootable kernel for you (linux-next).

**Comment by vincentbernat** [comment]
`minimal-config` will erase the current `.config`, so the `make tinyconfig` is useless. I have just pulled net-next and I am able to boot with any issue with `eudyptula-boot -k arch/x86/boot/bzImage`:

```
20240  make tinyconfig
20241  ~/code/perso/eudyptula-boot/minimal-configuration debug
20242  make -j4
20243  eudyptula-boot -k arch/x86/boot/bzImage
```

**Comment by vincentbernat** [comment]
I said `net-next`, but I've just tested with `linux-next` as well and it fails. I'll bisect the issue.

**Comment by vincentbernat** [comment]
So, the culprit is https://github.com/torvalds/linux/commit/fd0002870b453c58d0d8c195954f5049bc6675fb. As it is quite recent, I think this may be fixed during the next 9fs pull.

**Comment by jbernard** [comment]
Thanks Vincent!
